dist: trusty
warnings_are_errors: false
language: scala
scala:
   - 2.12.6
env:
    - GPG_EXECUTABLE=gpg
before_install:
    - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --no-use-agent --import; fi
    - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --no-use-agent --import-ownertrust; fi
script:
    - sbt clean coverage test webapiJVM/coverageReport &&
      sbt coverageAggregate
after_success:
    - sbt coveralls
deploy:
    -
        provider: script
        script: bash scripts/publish-js.sh
        skip_cleanup: true
        on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]\.[0-9]\.[0-9](-beta)?$
    -
        provider: script
        script: bash scripts/publish-java.sh
        skip_cleanup: true
        on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]\.[0-9]\.[0-9](-beta)?$
