swagger: '2.0'
info:
  title: API with Types
  version: ''
definitions:
  User:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      age:
        minimum: 0
        maximum: 99
        type: integer
    required:
    - firstName
    - lastName
    - age
paths:
  "/users/{id}":
    get:
      operationId: GET_users-id
      produces:
      - application/json
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/User"
    parameters:
    - type: string
      in: path
      name: id
      required: true
